### ISSUE TITLE
multiple tutorials are here

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl-tutorial#11]
the description line for the repo and the README contents imply this is one tutorial, rather than a set.  Both should be updated.

**Comment by vsoch** [comment]
It looks like the README is good to describe multiple, but the description and repository name just need tweaking.

**Comment by danielskatz** [comment]
I don't think we should change the repo name at this point, based on external links to it.

@yadudoc - can you change the description, from "Tutorial to demonstrate the use of Parsl" to "Tutorials to demonstrate the use of Parsl".

Then we could close this issue.

**Comment by kylechard** [comment]
I worry about changing the name too as I'm sure I won't be able to track down all the references. 

I've updated the description as Dan suggested. 

Thanks Vanessa and Dan.

**Comment by vsoch** [comment]
Thanks to you both!
